### ISSUE TITLE
Print the server path when starting

### ISSUE THREAD

**Issue by darko1002001** [uaihebert/uaiMockServer#39]
It would be nice to just print the server path in console when starting the server locally

also will be helpful to have a method getRootUrl() on the server instance when writing tests to get the configured route when starting/stopping the server, so we don't have to hardcode the path to the mock server in the tests.

**Comment by uaihebert** [comment]
Hello. 

I know this is super old, but I just implemented. It was committed here: 4197bb218000a3ae0747e1c8e49222c2392ff5a9 and 75547cc3538b4f5b922e22914eecd024f9bc111e

It will be on the next release.
