### ISSUE TITLE
Make Create backups of the config configurable

### ISSUE THREAD

**Issue by darko1002001** [uaihebert/uaiMockServer#40]
Right now i am getting a backup file every time i add a request or delete one.

It would be nice if this is configurable when starting the server so that we can turn it on or off.
I am using git to manage the config and i don't need the backups. it just creates too much files.

**Comment by uaihebert** [comment]
Solved.

https://github.com/uaihebert/uaiMockServer/commit/8491315630896aee11e66a74885ff3f4e5d8ca42
